import type { Metadata } from 'next';
import { Bayon, Merriweather_Sans } from 'next/font/google';
import '../../asset/root.css';
import NavigationBar from '@/components/global/components/NavigationBar';
import FooterSection from '@/components/global/components/footer-section';

const bayonFont = Bayon({
  variable: '--font-bayon',
  weight: ['400'],
  subsets: ['khmer'],
});

const merriweatherSans = Merriweather_Sans({
  variable: '--font-weather',
  subsets: ['cyrillic-ext'],
  style: ['italic', 'normal'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bayonFont.variable} ${merriweatherSans.variable} body-background`}
      >
        <NavigationBar />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
